language: java
jdk:
- oraclejdk8
script: mvn install
deploy:
  provider: releases
  skip_cleanup: true
  #file: /home/travis/build/ozlerhakan/mongolastic/target/mongolastic.jar
  on:
    tags: true
    all_branches: true
    repo: hakdogan/MongoAtlas

